default_config:

logger:
  default: warning
  logs:
    custom_components.fuelprices_dk: debug
    pybraendstofpriser: debug


# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
